version: '2'
services:
    blog-app:
        image: blog
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://blog-mariadb:3306/blog
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    blog-mariadb:
        extends:
            file: mariadb.yml
            service: blog-mariadb
